language: php

php:
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test